ci: misc workflow improvments

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -106,6 +106,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          persist-credentials: true
 
       - name: Set up Helm
         uses: azure/setup-helm@v3
@@ -115,30 +116,30 @@ jobs:
         run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
 
       - name: Package Helm chart
-        run: |
-          helm package charts/pfsense-exporter --version ${{ steps.get_version.outputs.VERSION }} --app-version ${{ steps.get_version.outputs.VERSION }}
+        run: helm package charts/pfsense-exporter --version ${{ steps.get_version.outputs.VERSION }} --app-version ${{ steps.get_version.outputs.VERSION }}
           
       - name: Upload Helm chart as release asset
-        uses: softprops/action-gh-release@v2
+        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
         with:
           files: pfsense-exporter-${{ steps.get_version.outputs.VERSION }}.tgz
 
       - name: Re-index Helm chart repository
         run: |
+          # Ensure we fail fast
+          set -e  
+
           # Set up git config
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
           # Stash the new chart for now so we can switch branches and update the index
-          git add pfsense-exporter-${{ steps.get_version.outputs.VERSION }}.tgz
-          git stash push -m "release_helm_chart" pfsense-exporter-${{ steps.get_version.outputs.VERSION }}.tgz
+          git stash push -m -u "release_helm_chart" pfsense-exporter-${{ steps.get_version.outputs.VERSION }}.tgz
           git fetch origin gh-pages
           git checkout gh-pages
           git stash pop
 
           # Update Helm repo index and remove the chart file
           helm repo index . --merge index.yaml --url https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/
-          git rm pfsense-exporter-${{ steps.get_version.outputs.VERSION }}.tgz -f
 
           # Commit and push the updated index
           git add index.yaml
