ci: improve helm chart release workflow (#8)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -106,6 +106,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          persist-credentials: true
 
       - name: Set up Helm
         uses: azure/setup-helm@v3
@@ -114,21 +115,34 @@ jobs:
         id: get_version
         run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
 
-      # This is required for chart-releaser
-      - name: Configure Git username and email
-        run: |
-          git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
-
       - name: Package Helm chart
-        run: |
-          mkdir -p .cr-release-packages
-          helm package charts/pfsense-exporter --version ${{ steps.get_version.outputs.VERSION }} --app-version ${{ steps.get_version.outputs.VERSION }} -d .cr-release-packages
+        run: helm package charts/pfsense-exporter --version ${{ steps.get_version.outputs.VERSION }} --app-version ${{ steps.get_version.outputs.VERSION }}
           
-      - name: Run chart-releaser
-        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
-        env:
-          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+      - name: Upload Helm chart as release asset
+        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
         with:
-          skip_packaging: true
-          mark_as_latest: false
+          files: pfsense-exporter-${{ steps.get_version.outputs.VERSION }}.tgz
+
+      - name: Re-index Helm chart repository
+        run: |
+          # Ensure we fail fast
+          set -e  
+
+          # Set up git config
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+          # Stash the new chart for now so we can switch branches and update the index
+          git stash push -m -u "release_helm_chart" pfsense-exporter-${{ steps.get_version.outputs.VERSION }}.tgz
+          git fetch origin gh-pages
+          git checkout gh-pages
+          git stash pop
+
+          # Update Helm repo index and remove the chart file
+          helm repo index . --merge index.yaml --url https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/
+
+          # Commit and push the updated index
+          git add index.yaml
+          git commit -m "chore(helm): add pfsense-exporter-${{ steps.get_version.outputs.VERSION }} to repo index"
+          git push origin gh-pages
+        
